apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}-configmap
data:
  config.json: |-
    {
{{- range $key, $val := .Values.json }}
{{ $key | quote | indent 6}}: {{ $val | quote }}
{{- end}}
    }
